package(default_visibility = ["//visibility:public"])


py_library(
    name = "extended_gl_view_widget",
    srcs = ["extended_gl_view_widget.py"],
    deps = [
    ],
)

py_library(
    name = "observable_list",
    srcs = ["observable_list.py"],
    deps = [],
)

py_library(
    name = "triangulate",
    srcs = ["triangulate.py"],
    deps = [],
)
